language: node_js
node_js:
  - "stable"
  - "5.7.0"
  - "0.12"
  - "0.10"
  - "iojs"
  - "iojs-v1.1.0"
branches:
  only:
    - master
script:
  - "npm run-script test"
  - "npm run-script cover"
  - "npm run-script lint"
